name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to push tags later

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build and bump dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@0.32.1
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} #
        run: |
          twine upload dist/*

      - name: Push changes and tags
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SlavaSkvortsov/flake8-close-io-buffers.git
          git push --follow-tags
